### PR TITLE
Fail gracefully when space switch controls are not found

### PR DESCRIPTION
**Pull request by miabrahams**
This allows loading .pkr files when the rig does not match exactly

### CODE REVIEW

**Comment by miquelcampos** [comment]
Hello, @miabrahams I am sorry for the late reply, I didn't see your PR until now. I will check it and merge ASAP.

Thanks for the contribution! :D

**Review by RafaelVillar — CHANGES_REQUESTED** [review]
Could you also print the error for the failed control? Or is it a benign reason for the error?

**Comment by miabrahams** [comment]
This error comes up when making changes to your rig without updating the anim picker. It's benign but a suggestion for how to fix it is a good idea.

**Review by RafaelVillar — APPROVED** [review]

**Comment by miquelcampos** [comment]
sorry for the delay merging this PR

**Pull request merged**
